spring.profiles.active=local

spring.jpa.hibernate.ddl-auto=update
spring.jpa.show-sql=true
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect

server.address=0.0.0.0
server.port=${PORT:8080}

cloudinary.cloud-name=dffbfayue
cloudinary.api-key=852246585836511
cloudinary.api-secret=JC0k2icIeWHczLN6Fqo5NbupnrU

spring.servlet.multipart.enabled=true
spring.servlet.multipart.max-file-size=10MB
spring.servlet.multipart.max-request-size=10MB