spring.datasource.url=jdbc:postgresql://ep-weathered-sound-app4bflg.c-7.us-east-1.aws.neon.tech/neondb?sslmode=require&channel_binding=require
spring.datasource.username=neondb_owner
spring.datasource.password=npg_4SgiEjv9IPed
spring.datasource.driver-class-name=org.postgresql.Driver